// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: sqlresponse.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace BloombergLP.Cdb2.ProtoBuf
{

    [global::ProtoBuf.ProtoContract(Name = @"CDB2_DBINFORESPONSE")]
    public partial class Cdb2Dbinforesponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"master", IsRequired = true)]
        public Nodeinfo Master { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"nodes")]
        public global::System.Collections.Generic.List<Nodeinfo> Nodes { get; } = new global::System.Collections.Generic.List<Nodeinfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"require_ssl")]
        public bool RequireSsl
        {
            get { return __pbn__RequireSsl.GetValueOrDefault(); }
            set { __pbn__RequireSsl = value; }
        }
        public bool ShouldSerializeRequireSsl() => __pbn__RequireSsl != null;
        public void ResetRequireSsl() => __pbn__RequireSsl = null;
        private bool? __pbn__RequireSsl;

        [global::ProtoBuf.ProtoContract(Name = @"nodeinfo")]
        public partial class Nodeinfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
            public string Name { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"number", IsRequired = true)]
            public int Number { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"incoherent", IsRequired = true)]
            public int Incoherent { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"room")]
            public int Room
            {
                get { return __pbn__Room.GetValueOrDefault(); }
                set { __pbn__Room = value; }
            }
            public bool ShouldSerializeRoom() => __pbn__Room != null;
            public void ResetRoom() => __pbn__Room = null;
            private int? __pbn__Room;

            [global::ProtoBuf.ProtoMember(5, Name = @"port")]
            public int Port
            {
                get { return __pbn__Port.GetValueOrDefault(); }
                set { __pbn__Port = value; }
            }
            public bool ShouldSerializePort() => __pbn__Port != null;
            public void ResetPort() => __pbn__Port = null;
            private int? __pbn__Port;

        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"CDB2_EFFECTS")]
    public partial class Cdb2Effects : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"num_affected", IsRequired = true)]
        public int NumAffected { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"num_selected", IsRequired = true)]
        public int NumSelected { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"num_updated", IsRequired = true)]
        public int NumUpdated { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"num_deleted", IsRequired = true)]
        public int NumDeleted { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"num_inserted", IsRequired = true)]
        public int NumInserted { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"CDB2_SQLRESPONSE")]
    public partial class Cdb2Sqlresponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"response_type", IsRequired = true)]
        public ResponseType ResponseType { get; set; } = ResponseType.ColumnNames;

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public global::System.Collections.Generic.List<Column> Values { get; } = new global::System.Collections.Generic.List<Column>();

        [global::ProtoBuf.ProtoMember(3, Name = @"dbinforesponse")]
        public Cdb2Dbinforesponse Dbinforesponse { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"error_code", IsRequired = true)]
        public CDB2ErrorCode ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"error_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorString
        {
            get { return __pbn__ErrorString ?? ""; }
            set { __pbn__ErrorString = value; }
        }
        public bool ShouldSerializeErrorString() => __pbn__ErrorString != null;
        public void ResetErrorString() => __pbn__ErrorString = null;
        private string __pbn__ErrorString;

        [global::ProtoBuf.ProtoMember(6, Name = @"effects")]
        public Cdb2Effects Effects { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"snapshot_info")]
        public Snapshotinfo SnapshotInfo { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"row_id")]
        public ulong RowId
        {
            get { return __pbn__RowId.GetValueOrDefault(); }
            set { __pbn__RowId = value; }
        }
        public bool ShouldSerializeRowId() => __pbn__RowId != null;
        public void ResetRowId() => __pbn__RowId = null;
        private ulong? __pbn__RowId;

        [global::ProtoBuf.ProtoMember(9, Name = @"features")]
        public global::System.Collections.Generic.List<CDB2ServerFeatures> Features { get; } = new global::System.Collections.Generic.List<CDB2ServerFeatures>();

        [global::ProtoBuf.ProtoMember(10, Name = @"info_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string InfoString
        {
            get { return __pbn__InfoString ?? ""; }
            set { __pbn__InfoString = value; }
        }
        public bool ShouldSerializeInfoString() => __pbn__InfoString != null;
        public void ResetInfoString() => __pbn__InfoString = null;
        private string __pbn__InfoString;

        [global::ProtoBuf.ProtoContract(Name = @"column")]
        public partial class Column : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"type")]
            [global::System.ComponentModel.DefaultValue(CDB2ColumnType.Integer)]
            public CDB2ColumnType Type
            {
                get { return __pbn__Type ?? CDB2ColumnType.Integer; }
                set { __pbn__Type = value; }
            }
            public bool ShouldSerializeType() => __pbn__Type != null;
            public void ResetType() => __pbn__Type = null;
            private CDB2ColumnType? __pbn__Type;

            [global::ProtoBuf.ProtoMember(2, Name = @"value", IsRequired = true)]
            public byte[] Value { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"isnull")]
            [global::System.ComponentModel.DefaultValue(false)]
            public bool Isnull
            {
                get { return __pbn__Isnull ?? false; }
                set { __pbn__Isnull = value; }
            }
            public bool ShouldSerializeIsnull() => __pbn__Isnull != null;
            public void ResetIsnull() => __pbn__Isnull = null;
            private bool? __pbn__Isnull;

        }

        [global::ProtoBuf.ProtoContract(Name = @"snapshotinfo")]
        public partial class Snapshotinfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"file", IsRequired = true)]
            public int File { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"offset", IsRequired = true)]
            public int Offset { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"CDB2_ColumnType")]
    public enum CDB2ColumnType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"INTEGER")]
        Integer = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"REAL")]
        Real = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CSTRING")]
        Cstring = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"BLOB")]
        Blob = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"DATETIME")]
        Datetime = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"INTERVALYM")]
        Intervalym = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"INTERVALDS")]
        Intervalds = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"DATETIMEUS")]
        Datetimeus = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"INTERVALDSUS")]
        Intervaldsus = 10,
    }

    [global::ProtoBuf.ProtoContract(Name = @"CDB2_ErrorCode")]
    public enum CDB2ErrorCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"OK")]
        Ok = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"DUP_OLD")]
        DupOld = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CONNECT_ERROR")]
        ConnectError = -1,
        [global::ProtoBuf.ProtoEnum(Name = @"NOTCONNECTED")]
        Notconnected = -2,
        [global::ProtoBuf.ProtoEnum(Name = @"PREPARE_ERROR")]
        PrepareError = -3,
        [global::ProtoBuf.ProtoEnum(Name = @"PREPARE_ERROR_OLD")]
        PrepareErrorOld = 1003,
        [global::ProtoBuf.ProtoEnum(Name = @"IO_ERROR")]
        IoError = -4,
        [global::ProtoBuf.ProtoEnum(Name = @"INTERNAL")]
        Internal = -5,
        [global::ProtoBuf.ProtoEnum(Name = @"NOSTATEMENT")]
        Nostatement = -6,
        [global::ProtoBuf.ProtoEnum(Name = @"BADCOLUMN")]
        Badcolumn = -7,
        [global::ProtoBuf.ProtoEnum(Name = @"BADSTATE")]
        Badstate = -8,
        [global::ProtoBuf.ProtoEnum(Name = @"ASYNCERR")]
        Asyncerr = -9,
        [global::ProtoBuf.ProtoEnum(Name = @"OK_ASYNC")]
        OkAsync = -10,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_ID")]
        InvalidId = -12,
        [global::ProtoBuf.ProtoEnum(Name = @"RECORD_OUT_OF_RANGE")]
        RecordOutOfRange = -13,
        [global::ProtoBuf.ProtoEnum(Name = @"REJECTED")]
        Rejected = -15,
        [global::ProtoBuf.ProtoEnum(Name = @"STOPPED")]
        Stopped = -16,
        [global::ProtoBuf.ProtoEnum(Name = @"BADREQ")]
        Badreq = -17,
        [global::ProtoBuf.ProtoEnum(Name = @"DBCREATE_FAILED")]
        DbcreateFailed = -18,
        [global::ProtoBuf.ProtoEnum(Name = @"THREADPOOL_INTERNAL")]
        ThreadpoolInternal = -20,
        [global::ProtoBuf.ProtoEnum(Name = @"READONLY")]
        Readonly = -21,
        [global::ProtoBuf.ProtoEnum(Name = @"NOMASTER")]
        Nomaster = -101,
        [global::ProtoBuf.ProtoEnum(Name = @"NOTSERIAL")]
        Notserial = 230,
        [global::ProtoBuf.ProtoEnum(Name = @"SCHEMACHANGE")]
        Schemachange = 240,
        [global::ProtoBuf.ProtoEnum(Name = @"UNTAGGED_DATABASE")]
        UntaggedDatabase = -102,
        [global::ProtoBuf.ProtoEnum(Name = @"CONSTRAINTS")]
        Constraints = -103,
        [global::ProtoBuf.ProtoEnum(Name = @"DEADLOCK")]
        Deadlock = 203,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAN_IO_ERROR")]
        TranIoError = -105,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCESS")]
        Access = -106,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAN_MODE_UNSUPPORTED")]
        TranModeUnsupported = -107,
        [global::ProtoBuf.ProtoEnum(Name = @"MASTER_TIMEOUT")]
        MasterTimeout = -109,
        [global::ProtoBuf.ProtoEnum(Name = @"APPSOCK_LIMIT")]
        AppsockLimit = -110,
        [global::ProtoBuf.ProtoEnum(Name = @"WRONG_DB")]
        WrongDb = -111,
        [global::ProtoBuf.ProtoEnum(Name = @"VERIFY_ERROR")]
        VerifyError = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"FKEY_VIOLATION")]
        FkeyViolation = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"NULL_CONSTRAINT")]
        NullConstraint = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"CONV_FAIL")]
        ConvFail = 113,
        [global::ProtoBuf.ProtoEnum(Name = @"NONKLESS")]
        Nonkless = 114,
        [global::ProtoBuf.ProtoEnum(Name = @"MALLOC")]
        Malloc = 115,
        [global::ProtoBuf.ProtoEnum(Name = @"NOTSUPPORTED")]
        Notsupported = 116,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAN_TOO_BIG")]
        TranTooBig = 202,
        [global::ProtoBuf.ProtoEnum(Name = @"DUPLICATE")]
        Duplicate = 299,
        [global::ProtoBuf.ProtoEnum(Name = @"TZNAME_FAIL")]
        TznameFail = 401,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANGENODE")]
        Changenode = 402,
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 300,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ResponseHeader
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SQL_RESPONSE")]
        SqlResponse = 1002,
        [global::ProtoBuf.ProtoEnum(Name = @"DBINFO_RESPONSE")]
        DbinfoResponse = 1005,
        [global::ProtoBuf.ProtoEnum(Name = @"SQL_EFFECTS")]
        SqlEffects = 1006,
        [global::ProtoBuf.ProtoEnum(Name = @"SQL_RESPONSE_PING")]
        SqlResponsePing = 1007,
        [global::ProtoBuf.ProtoEnum(Name = @"SQL_RESPONSE_PONG")]
        SqlResponsePong = 1008,
        [global::ProtoBuf.ProtoEnum(Name = @"SQL_RESPONSE_TRACE")]
        SqlResponseTrace = 1009,
        [global::ProtoBuf.ProtoEnum(Name = @"SQL_RESPONSE_SSL")]
        SqlResponseSsl = 1010,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ResponseType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"COLUMN_NAMES")]
        ColumnNames = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"COLUMN_VALUES")]
        ColumnValues = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"LAST_ROW")]
        LastRow = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"COMDB2_INFO")]
        Comdb2Info = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"SP_TRACE")]
        SpTrace = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"SP_DEBUG")]
        SpDebug = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum CDB2ServerFeatures
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SKIP_INTRANS_RESULTS")]
        SkipIntransResults = 1,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
